"""Shared utilities for Polymarket Sports Analytics."""

from utils.shared_utils import (
    OUTPUT_DIR,
    LATE_PICK_THRESHOLD,
    MIN_WIN_PCT,
    MIN_GAMES_FOR_WIN_PCT,
    MIN_GAMES,
    MIN_WINS,
    SPORTS_CONFIG,
    get_seasons,
    get_season,
    get_csv_max_week,
    get_max_week,
    get_season_week_limit,
    get_week_dates,
    get_current_week,
    get_last_n_weeks,
    normalize_is_correct,
    coerce_numeric_series,
    parse_game_teams,
    filter_by_season,
    filter_by_weeks,
    get_output_filename,
)
from utils.excel_utils import (
    GREEN_FILL,
    RED_FILL,
    YELLOW_FILL,
    HEADER_FILL,
    HEADER_FONT,
    apply_result_color,
    apply_header_style,
    create_hyperlink_cell,
    progress_bar,
    print_progress,
    format_time,
    calculate_eta,
)
from utils.menu_utils import (
    select_sport,
    select_season,
    select_time_period,
    select_resolution_status,
)

__all__ = [
    # shared_utils
    "OUTPUT_DIR",
    "LATE_PICK_THRESHOLD",
    "MIN_WIN_PCT",
    "MIN_GAMES_FOR_WIN_PCT",
    "MIN_GAMES",
    "MIN_WINS",
    "SPORTS_CONFIG",
    "get_seasons",
    "get_season",
    "get_csv_max_week",
    "get_max_week",
    "get_season_week_limit",
    "get_week_dates",
    "get_current_week",
    "get_last_n_weeks",
    "normalize_is_correct",
    "coerce_numeric_series",
    "parse_game_teams",
    "filter_by_season",
    "filter_by_weeks",
    "get_output_filename",
    # excel_utils
    "GREEN_FILL",
    "RED_FILL",
    "YELLOW_FILL",
    "HEADER_FILL",
    "HEADER_FONT",
    "apply_result_color",
    "apply_header_style",
    "create_hyperlink_cell",
    "progress_bar",
    "print_progress",
    "format_time",
    "calculate_eta",
    # menu_utils
    "select_sport",
    "select_season",
    "select_time_period",
    "select_resolution_status",
]
